Getting and Cleaning data - Quiz 4
========================================================
  
Soutions for the Quiz 4 questions:
  
```{r}
if (grepl("quiz4$", getwd()) == FALSE) {
  setwd(paste0(getwd(), "/quiz4"))
}
```

## Question 1
```{r}
filename = "question1_file.csv"
if (!file.exists(filename)) {
  retval = download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv",
                         destfile = filename,
                         method = "curl")
}
housing = read.csv(filename, header=T)

retval = strsplit(names(housing), "wgtp")
retval[[123]]
```

## Question 2
```{r}
filename = "question2_file.csv"
if (!file.exists(filename)) {
  retval = download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv",
                         destfile = filename,
                         method = "curl")
}
GDP = read.csv(filename, header=T)
GDP.numbers = as.character(GDP$X.3[5:194])
GDP.numbers = as.numeric(gsub("[, ]", "", GDP.numbers, fixed=F))

mean(GDP.numbers)
```

## Question 3
```{r}
countryNames = as.character(GDP$X.2)
suppressWarnings(grep("^United",countryNames))
```

## Question 4
```{r}
GDP.ranked = GDP[5:194,]
filename = "question4_file.csv"
if (!file.exists(filename)) {
  retval = download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv",
                         destfile = filename,
                         method = "curl")
}
EDU = read.csv(filename, header=T)

GDP.ranked$X <- as.character(GDP.ranked$X)
EDU$CountryCode <- as.character(EDU$CountryCode)

ret = merge(GDP.ranked, EDU, by.x="X", by.y="CountryCode")
ret$Special.Notes <- as.character(ret$Special.Notes)
length(grep("Fiscal year end: June", ret$Special.Notes, value=T))
```

## Question 5
```{r}
library(quantmod)
library(lubridate)
amzn = getSymbols("AMZN",auto.assign=FALSE)
sampleTimes = index(amzn) 

sum(year(sampleTimes) == 2012)
sum((wday(sampleTimes) == 2) & (year(sampleTimes) == 2012))
```
